version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
     - POSTGRES_DB=my_db
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  # only exec this: docker-compose up -d pgadmin
  pgadmin:
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=root@admin.com
     - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    depends_on:
      - postgres

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
     - MYSQL_DATABASE=my_db
     - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
  # only exec this: docker-compose up -d phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - PMA_HOST=mysql
    ports:
      - '8080:80'
    depends_on:
      - mysql
